### ISSUE TITLE
'window is not defined' when rendering on server

### ISSUE THREAD

**Issue by austinmao** [milworm/react-progress-2#4]
Using react-progress-2 with https://github.com/erikras/react-redux-universal-hot-example results in error below with v4.2.0

```
[1] [piping] error given was: ReferenceError: window is not defined
[1]     at [object Object].componentWillMount (/Users/austinmao/Sites/aditive-frontend/node_modules/react-progress-2/lib/main.js:73:9)
[1]     at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactCompositeComponent.js:210:12)
[1]     at [object Object].wrapper [as mountComponent] (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactPerf.js:66:21)
[1]     at Object.ReactReconciler.mountComponent (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactReconciler.js:37:35)
[1]     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactMultiChild.js:241:44)
[1]     at ReactDOMComponent.Mixin._createContentMarkup (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactDOMComponent.js:591:32)
[1]     at ReactDOMComponent.Mixin.mountComponent (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactDOMComponent.js:479:29)
[1]     at Object.ReactReconciler.mountComponent (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactReconciler.js:37:35)
[1]     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactMultiChild.js:241:44)
[1]     at ReactDOMComponent.Mixin._createContentMarkup (/Users/austinmao/Sites/aditive-frontend/node_modules/react/lib/ReactDOMComponent.js:591:32)
```

Maybe need to put `window` ref in `componentDidMount`?

**Comment by milworm** [comment]
oops ...  just published a fix in 4.2.1
thanks for report!

**Comment by austinmao** [comment]
Wow you're fast. I just made a pull request.

**Comment by austinmao** [comment]
Please don't forget to republish to npm

**Comment by milworm** [comment]
yup!
